version: '3'

services:
  parser:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - selenium

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    environment:
      - VNC_NO_PASSWORD=1
    ports:
      - "4444:4444"
      - "5900:5900"

volumes:
  postgres_data:
