version: '3'

services:
  parser:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  selenium:
    image: selenium/standalone-chrome:latest
    depends_on:
      - parser
    ports:
      - "4444:4444"
      - "5900:5900"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
